Update hst-install-debian.sh
fix:

...
[ * ] Configuring System IP...
[ * ] Installing remaining software updates...
Job for hestia.service failed because the control process exited with error code.
See "systemctl status hestia.service" and "journalctl -xeu hestia.service" for details.
Error: hestia start failed